//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Security.Authentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserApplication
    {
        public string UserId { get; set; }
        public string ApplicationId { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual User User { get; set; }
    }
}
