//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantAchievementsAndAssociations
    {
        public int ApplicantAchievementsAndAssociationsId { get; set; }
        public Nullable<int> Type { get; set; }
        public string Description { get; set; }
        public Nullable<int> ApplicantId { get; set; }
        public Nullable<int> JobId { get; set; }
    }
}
