//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceException
    {
        public int AttendanceExceptionId { get; set; }
        public int UserId { get; set; }
        public int EarlyInLastPeriod { get; set; }
        public int LateInLastPeriod { get; set; }
        public int EarlyOutLastPeriod { get; set; }
        public int LateOutLastPeriod { get; set; }
        public int WorkNotScheduedLastPeriod { get; set; }
        public int AbsentLastPeriod { get; set; }
        public int LunchOverLastPeriod { get; set; }
        public int LunchUnderLastPeriod { get; set; }
        public int EarlyInYTD { get; set; }
        public int LateInYTD { get; set; }
        public int EarlyOutYTD { get; set; }
        public int LateOutYTD { get; set; }
        public int WorkNSYTD { get; set; }
        public int AbsentYTD { get; set; }
        public int LunchOverYTD { get; set; }
        public int LunchUnderYTD { get; set; }
        public int EarlyInLastYear { get; set; }
        public int LateInLastYear { get; set; }
        public int EarlyOutLastYear { get; set; }
        public int LateOutLastYear { get; set; }
        public int WorkNotScheduledLastYear { get; set; }
        public int AbsentLastYear { get; set; }
        public int LunchOverLastYear { get; set; }
        public int LunchUnderLastYear { get; set; }
        public int EarlyInYearBeforeLast { get; set; }
        public int LateInYearBeforeLast { get; set; }
        public int EarlyOutYearBeforeLast { get; set; }
        public int LateOutYearBeforeLast { get; set; }
        public int WorkNotScheduledYearBeforeLast { get; set; }
        public int AbsentYearBeforeLast { get; set; }
        public int LunchOverYearBeforeLast { get; set; }
        public int LunchUnderYearBeforeLast { get; set; }
        public int EarlyInPerpetual { get; set; }
        public int LateInPerpetual { get; set; }
        public int EarlyOutPerpetual { get; set; }
        public int LateOutPerpetual { get; set; }
        public int WorkNotScheduledPerpetual { get; set; }
        public int AbsentPerpetual { get; set; }
        public int LunchOverPerpetual { get; set; }
        public int LunchUnderPerpetual { get; set; }
        public int CompanyId { get; set; }
    }
}
