//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendaceId { get; set; }
        public int UserId { get; set; }
        public int PayTypeId { get; set; }
        public string PayType { get; set; }
        public string PayCode { get; set; }
        public int TimeType { get; set; }
        public int LastPeriodMinutes { get; set; }
        public int YTDMinutes { get; set; }
        public int LastYearMinutes { get; set; }
        public int YearBeforeLastMinutes { get; set; }
        public int PerpetualMinutes { get; set; }
        public int LastPeriodDays { get; set; }
        public int YTDDays { get; set; }
        public int LastYearDays { get; set; }
        public int YearBeforeLastDays { get; set; }
        public int PerpetualDays { get; set; }
        public int CompanyId { get; set; }
    }
}
