//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateOfferLetter
    {
        public int CandidateOfferLetterId { get; set; }
        public System.Guid CandidateOfferLetterCode { get; set; }
        public int CompanyId { get; set; }
        public int CandidateId { get; set; }
        public int JobProfileId { get; set; }
        public string CandidateOfferLetterContent { get; set; }
        public bool LetterMailtoRecruiter { get; set; }
        public bool LetterMailtoCandidate { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
