//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClockDeviceAttendanceLog
    {
        public int ClockAttendanceLogId { get; set; }
        public int ClockDeviceId { get; set; }
        public string DeviceNumber { get; set; }
        public string IPAdderess { get; set; }
        public string PunchType { get; set; }
        public int UserId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> Level4Id { get; set; }
        public Nullable<int> Level5Id { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public bool IsUploaded { get; set; }
        public bool IsSms { get; set; }
        public bool IsEmail { get; set; }
        public Nullable<int> WorkCode { get; set; }
        public Nullable<int> Reserved { get; set; }
        public int CompanyId { get; set; }
    
        public virtual ClockDevice ClockDevice { get; set; }
    }
}
