//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClockProfile
    {
        public int ClockProfileId { get; set; }
        public int UserId { get; set; }
        public string EmployeeName { get; set; }
        public string EmailId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> PayPeriodId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string JobId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> ShiftMasterId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<int> ClockLocationId { get; set; }
        public string ReporToUserId { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Remember { get; set; }
        public int CompanyId { get; set; }
    
        public virtual ClockLocation ClockLocation { get; set; }
        public virtual PayPeriods PayPeriods { get; set; }
    }
}
