//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClockDevicesAssigndEmployee
    {
        public int ClockDeviceAssignedUserId { get; set; }
        public int CompanyId { get; set; }
        public int ClockDeviceId { get; set; }
        public string UserId { get; set; }
    
        public virtual ClockDevice ClockDevice { get; set; }
    }
}
