//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClockDevice
    {
        public ClockDevice()
        {
            this.ClockDatas = new HashSet<ClockData>();
            this.ClockDatas1 = new HashSet<ClockData>();
            this.ClockDataAudits = new HashSet<ClockDataAudit>();
            this.ClockDataAudits1 = new HashSet<ClockDataAudit>();
            this.ClockDeviceAttendanceLogs = new HashSet<ClockDeviceAttendanceLog>();
            this.ClockDevicesAssigndEmployees = new HashSet<ClockDevicesAssigndEmployee>();
        }
    
        public int ClockDeviceId { get; set; }
        public int CompanyId { get; set; }
        public string DeviceNumber { get; set; }
        public string DeviceIP { get; set; }
        public int ClockLocationId { get; set; }
        public Nullable<int> ConnectionModeId { get; set; }
        public string IPPort { get; set; }
        public string MachineSN { get; set; }
        public Nullable<int> BaudRate { get; set; }
        public Nullable<int> RSPort { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<ClockData> ClockDatas { get; set; }
        public virtual ICollection<ClockData> ClockDatas1 { get; set; }
        public virtual ICollection<ClockDataAudit> ClockDataAudits { get; set; }
        public virtual ICollection<ClockDataAudit> ClockDataAudits1 { get; set; }
        public virtual ICollection<ClockDeviceAttendanceLog> ClockDeviceAttendanceLogs { get; set; }
        public virtual ICollection<ClockDevicesAssigndEmployee> ClockDevicesAssigndEmployees { get; set; }
    }
}
