//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClockLocation
    {
        public ClockLocation()
        {
            this.ClockDatas = new HashSet<ClockData>();
            this.ClockDatas1 = new HashSet<ClockData>();
            this.ClockDataAudits = new HashSet<ClockDataAudit>();
            this.ClockDataAudits1 = new HashSet<ClockDataAudit>();
            this.ClockProfiles = new HashSet<ClockProfile>();
        }
    
        public int ClockLocationId { get; set; }
        public System.Guid LocationCode { get; set; }
        public string LocationName { get; set; }
        public int CmpanyId { get; set; }
    
        public virtual ICollection<ClockData> ClockDatas { get; set; }
        public virtual ICollection<ClockData> ClockDatas1 { get; set; }
        public virtual ICollection<ClockDataAudit> ClockDataAudits { get; set; }
        public virtual ICollection<ClockDataAudit> ClockDataAudits1 { get; set; }
        public virtual ICollection<ClockProfile> ClockProfiles { get; set; }
    }
}
