//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyLevelSecurity
    {
        public int CompanyLevelSecurityId { get; set; }
        public Nullable<System.Guid> CompanyLevelSecurityCode { get; set; }
        public int CompanyId { get; set; }
        public int RoleId { get; set; }
        public bool CanHire { get; set; }
        public bool CanViewHires { get; set; }
        public bool CanAccessDashboard { get; set; }
        public Nullable<int> EmployeeFilterCriteriaId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual CompanyInfo CompanyInfo { get; set; }
    }
}
