//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompensatoryTimePlan
    {
        public CompensatoryTimePlan()
        {
            this.CompensatoryEmployeeHistories = new HashSet<CompensatoryEmployeeHistory>();
            this.TimesheetPolicies = new HashSet<TimesheetPolicy>();
        }
    
        public int CompensatoryId { get; set; }
        public System.Guid CompensatoryCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> CompensatoryBalance { get; set; }
        public Nullable<decimal> RegHoursFactor { get; set; }
        public Nullable<decimal> OTHoursFactor { get; set; }
        public Nullable<decimal> DTHoursFactor { get; set; }
        public Nullable<byte> Distribute { get; set; }
        public Nullable<byte> DistributeTo { get; set; }
        public Nullable<byte> DistributePeriod { get; set; }
        public Nullable<byte> DistributeAmount { get; set; }
        public Nullable<int> DistributeAfterAmount { get; set; }
        public int CompanyId { get; set; }
    
        public virtual ICollection<CompensatoryEmployeeHistory> CompensatoryEmployeeHistories { get; set; }
        public virtual ICollection<TimesheetPolicy> TimesheetPolicies { get; set; }
    }
}
