//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompensationProfile
    {
        public int CompensationProfileId { get; set; }
        public Nullable<System.Guid> CompensationProfileCode { get; set; }
        public string SalaryGrade { get; set; }
        public Nullable<int> BenefitGroup { get; set; }
        public string Stock { get; set; }
        public decimal OtherCashComp { get; set; }
        public string PTOPlan { get; set; }
        public string OtherBenefits { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> WageType { get; set; }
        public Nullable<int> WageUnit { get; set; }
        public Nullable<decimal> WageAmount { get; set; }
        public Nullable<decimal> Commissions { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> AnnualizedPay { get; set; }
        public string Title { get; set; }
    }
}
