//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyAnnouncement
    {
        public int CompanyAnnouncementId { get; set; }
        public System.Guid CompanyAnnouncementCode { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> PublishStartDate { get; set; }
        public Nullable<System.DateTime> PublishEndDate { get; set; }
        public Nullable<bool> AcknowledgementReq { get; set; }
        public Nullable<int> AttachmentId { get; set; }
        public Nullable<bool> IsDraft { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
