//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentSendType
    {
        public DocumentSendType()
        {
            this.DocumentBasicCriterias = new HashSet<DocumentBasicCriteria>();
        }
    
        public int DocumentSendTypeId { get; set; }
        public string DocumentSendTypeName { get; set; }
    
        public virtual ICollection<DocumentBasicCriteria> DocumentBasicCriterias { get; set; }
    }
}
