//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentBasicCriteria
    {
        public int DocumentBasicCriteriaId { get; set; }
        public Nullable<int> CompanyDocumentId { get; set; }
        public Nullable<int> DocumentSendTypeId { get; set; }
        public Nullable<int> SelectedCriteriaListId { get; set; }
    
        public virtual DocumentSendType DocumentSendType { get; set; }
    }
}
