//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeGoal
    {
        public int EmployeeGoalId { get; set; }
        public Nullable<System.Guid> AssignedTo { get; set; }
        public Nullable<System.Guid> AssignedBy { get; set; }
        public string Status { get; set; }
        public string GoalDescription { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Indicator { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<int> Reminder { get; set; }
        public Nullable<double> Incentive { get; set; }
        public Nullable<bool> Prorate { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public bool Isrecurrenceschedule { get; set; }
        public int Recurrenceschedule { get; set; }
        public bool IsExcludeSunday { get; set; }
        public bool IsExcludeSaturdaysunday { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<bool> IsOneTimeGoal { get; set; }
        public Nullable<bool> IsGoalIncentive { get; set; }
        public string ClientTimeZone { get; set; }
        public System.DateTime ClientDateTime { get; set; }
        public Nullable<bool> Exclude { get; set; }
    }
}
