//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDependent
    {
        public int EmployeeDependentId { get; set; }
        public int CompanyId { get; set; }
        public int UserId { get; set; }
        public System.Guid EmployeeDependentCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<int> Suffix { get; set; }
        public string Alias { get; set; }
        public Nullable<int> Salutation { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Zip { get; set; }
        public string HomeEmail { get; set; }
        public string HomePhone { get; set; }
        public string CellPhone { get; set; }
        public string SSN { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> RelationShip { get; set; }
        public Nullable<bool> ImputedIncome { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<bool> Smoker { get; set; }
        public Nullable<bool> Student { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
