//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeNoConfiguration
    {
        public int EmployeeNoId { get; set; }
        public System.Guid EmployeeNoCode { get; set; }
        public int CompanyId { get; set; }
        public string Prefix { get; set; }
        public int StartValue { get; set; }
        public int IncrementValue { get; set; }
        public string CurrentValue { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
