//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeW4Form
    {
        public int Employeew4formId { get; set; }
        public int UserId { get; set; }
        public int CompanyId { get; set; }
        public string PersonalAllowancesA { get; set; }
        public Nullable<int> PersonalAllowancesB { get; set; }
        public string PersonalAllowancesC { get; set; }
        public Nullable<int> PersonalAllowancesD { get; set; }
        public string PersonalAllowancesE { get; set; }
        public string PersonalAllowancesF { get; set; }
        public string PersonalAllowancesG { get; set; }
        public string PersonalAllowancesH { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SSNNO { get; set; }
        public string HomeAddress { get; set; }
        public string CityTownStateZip { get; set; }
        public Nullable<bool> EmployeesWithHolding3 { get; set; }
        public Nullable<bool> EmployeesWithHolding4 { get; set; }
        public Nullable<decimal> EmployeesWithHolding5 { get; set; }
        public Nullable<decimal> EmployeesWithHolding6 { get; set; }
        public string EmployeesWithHolding7 { get; set; }
        public Nullable<int> EmployeeSignId { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public string EmployerAddress { get; set; }
        public string EmployeeOfficeCode { get; set; }
        public string IdentificationNo { get; set; }
        public Nullable<decimal> Deductions1 { get; set; }
        public Nullable<decimal> Deductions2 { get; set; }
        public Nullable<decimal> Deductions3 { get; set; }
        public Nullable<decimal> Deductions4 { get; set; }
        public Nullable<decimal> Deductions5 { get; set; }
        public Nullable<decimal> Deductions6 { get; set; }
        public Nullable<decimal> Deductions7 { get; set; }
        public Nullable<decimal> Deductions8 { get; set; }
        public Nullable<decimal> Deductions9 { get; set; }
        public Nullable<decimal> Deductions10 { get; set; }
        public string Earnings1 { get; set; }
        public string Earnings2 { get; set; }
        public string Earnings3 { get; set; }
        public string Earnings4 { get; set; }
        public string Earnings5 { get; set; }
        public string Earnings6 { get; set; }
        public Nullable<decimal> Earnings7 { get; set; }
        public Nullable<decimal> Earnings8 { get; set; }
        public Nullable<decimal> Earnings9 { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual RegisteredUsers RegisteredUsers { get; set; }
    }
}
