//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAlert
    {
        public int EmployeeAlertId { get; set; }
        public int AlertTemplateId { get; set; }
        public int EmployeeId { get; set; }
        public string EmployeeEmail { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> SendDateInterval { get; set; }
    }
}
