//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionLog
    {
        public int ID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Type { get; set; }
        public string Message { get; set; }
        public string StackTrace { get; set; }
        public string ExceptionSource { get; set; }
        public string MachineName { get; set; }
        public string CallStack { get; set; }
        public string AppDomainName { get; set; }
        public string AssemblyName { get; set; }
        public string AssemblyVersion { get; set; }
        public string ThreadID { get; set; }
        public string ThreadUser { get; set; }
    }
}
