//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseType
    {
        public ExpenseType()
        {
            this.ExpenseEmployees = new HashSet<ExpenseEmployee>();
        }
    
        public int ExpenseTypeId { get; set; }
        public System.Guid ExpenseTypeCode { get; set; }
        public string ExpenseType1 { get; set; }
        public Nullable<double> MaxAmount { get; set; }
        public string per { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> ISMileage { get; set; }
        public string GLCode { get; set; }
        public int CompanyId { get; set; }
    
        public virtual ICollection<ExpenseEmployee> ExpenseEmployees { get; set; }
    }
}
