//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseEmployee
    {
        public int ExpenseId { get; set; }
        public int ExpenseReportId { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public int ExpenseTypeId { get; set; }
        public string PaymentMode { get; set; }
        public string Notes { get; set; }
        public Nullable<double> Amount { get; set; }
        public string DocumentName { get; set; }
        public string ContentType { get; set; }
        public byte[] Attachments { get; set; }
        public string Merchant { get; set; }
        public Nullable<int> GLCode { get; set; }
        public int CompanyId { get; set; }
    
        public virtual ExpenseReport ExpenseReport { get; set; }
        public virtual ExpenseType ExpenseType { get; set; }
    }
}
