//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public int FormId { get; set; }
        public System.Guid FormCode { get; set; }
        public string FormName { get; set; }
        public string DisplayName { get; set; }
        public int ModuleId { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string RouteAttribute { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> OrderNo { get; set; }
    
        public virtual Module Module { get; set; }
    }
}
