//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayGroup
    {
        public int HolidayGroupId { get; set; }
        public System.Guid HolidayGroupCode { get; set; }
        public string HolidayGroupName { get; set; }
        public string HolidayDescription { get; set; }
        public int CompanyId { get; set; }
    }
}
