//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTABLES
    {
        public int HtableId { get; set; }
        public string HTABLES_TABLE { get; set; }
        public string CODE { get; set; }
        public string HTABLES_DESC { get; set; }
        public string C1 { get; set; }
        public string S1 { get; set; }
        public Nullable<bool> T1 { get; set; }
        public Nullable<bool> CAN_DELETE { get; set; }
        public Nullable<bool> SPECIALSCX { get; set; }
        public string COMPANY { get; set; }
        public Nullable<int> SecID { get; set; }
        public string ExternalCode { get; set; }
    }
}
