//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportMap
    {
        public int ImportMapId { get; set; }
        public string ImportMapName { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public string Format { get; set; }
        public short FieldPosition { get; set; }
        public Nullable<short> StartPosition { get; set; }
        public Nullable<short> FieldLength { get; set; }
        public Nullable<bool> DefProfCode { get; set; }
        public string Delimeter { get; set; }
        public Nullable<bool> Trans { get; set; }
        public Nullable<int> RecLength { get; set; }
        public bool Header { get; set; }
        public string StringFormat { get; set; }
        public bool RightJustification { get; set; }
        public int CompanyId { get; set; }
    }
}
