//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview
    {
        public Interview()
        {
            this.JobInterviewers = new HashSet<JobInterviewers>();
        }
    
        public int InterviewId { get; set; }
        public System.Guid InterviewCode { get; set; }
        public int JobProfileId { get; set; }
        public int CompanyId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> InterviewRoom { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> InterviewerId { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public Nullable<System.DateTime> InterviewTime { get; set; }
        public string CandidateInstructions { get; set; }
        public string InterviewerInstructions { get; set; }
        public Nullable<bool> SendInterviewerEmail { get; set; }
        public Nullable<bool> SendCandidateEmail { get; set; }
        public string Feedback { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<JobInterviewers> JobInterviewers { get; set; }
    }
}
