//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplied
    {
        public int JobApplicantId { get; set; }
        public int JobProfileId { get; set; }
        public Nullable<System.DateTime> AppliedOn { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> Status { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsHired { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual JobApplicant JobApplicant { get; set; }
        public virtual JobProfile JobProfile { get; set; }
    }
}
