//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplicant
    {
        public JobApplicant()
        {
            this.JobApplied = new HashSet<JobApplied>();
        }
    
        public int JobApplicantId { get; set; }
        public Nullable<System.Guid> JobApplicantCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string ApplicantDescription { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string City { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Phone { get; set; }
        public Nullable<int> ResumeAttachmentId { get; set; }
        public string ResumeText { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<JobApplied> JobApplied { get; set; }
    }
}
