//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobProfile
    {
        public JobProfile()
        {
            this.JobApplied = new HashSet<JobApplied>();
            this.JobDuties = new HashSet<JobDuties>();
            this.JobPME = new HashSet<JobPME>();
            this.JobQualification = new HashSet<JobQualification>();
            this.RecruitingQuestions = new HashSet<RecruitingQuestions>();
        }
    
        public int JobProfileId { get; set; }
        public System.Guid JobProfileCode { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string JobCode { get; set; }
        public string Title { get; set; }
        public string CityStateOrZipCode { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> JobCategory { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<bool> IsRequisiton { get; set; }
        public Nullable<int> PageVisitorCount { get; set; }
        public Nullable<int> HiringManager { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<bool> BasicInfo { get; set; }
        public Nullable<bool> Education { get; set; }
        public Nullable<bool> Employment { get; set; }
        public Nullable<bool> Certification { get; set; }
        public Nullable<bool> Skill { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string ManagerComments { get; set; }
        public Nullable<bool> ManagerActionFlag { get; set; }
    
        public virtual ICollection<JobApplied> JobApplied { get; set; }
        public virtual ICollection<JobDuties> JobDuties { get; set; }
        public virtual ICollection<JobPME> JobPME { get; set; }
        public virtual ICollection<JobQualification> JobQualification { get; set; }
        public virtual ICollection<RecruitingQuestions> RecruitingQuestions { get; set; }
    }
}
