//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobQualification
    {
        public JobQualification()
        {
            this.JobProfile = new HashSet<JobProfile>();
        }
    
        public int JobQualificationId { get; set; }
        public System.Guid JobQualificationCode { get; set; }
        public int CompanyId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Type { get; set; }
        public string SubjectArea { get; set; }
        public string Proficiency { get; set; }
        public Nullable<decimal> Years { get; set; }
        public string LastUsed { get; set; }
        public Nullable<bool> Mandatory { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<JobProfile> JobProfile { get; set; }
    }
}
