//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailingInfo
    {
        public int MailId { get; set; }
        public System.Guid MailCode { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string MailSubject { get; set; }
        public string MailFrom { get; set; }
        public string MailRecipientTo { get; set; }
        public string MailRecipientBCC { get; set; }
        public string MailRecipinetCC { get; set; }
        public string MailContent { get; set; }
        public Nullable<System.DateTime> MailSentOn { get; set; }
        public bool MailStatus { get; set; }
        public Nullable<int> MailCount { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
