//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.Forms = new HashSet<Form>();
        }
    
        public int ModuleId { get; set; }
        public System.Guid ModuleCode { get; set; }
        public string ModuleName { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string RouteAttributes { get; set; }
    
        public virtual ICollection<Form> Forms { get; set; }
    }
}
