//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleLevelSecurity
    {
        public int ModuleLevelSecurityId { get; set; }
        public System.Guid ModuleLevelSecurityCode { get; set; }
        public int CompanyId { get; set; }
        public int ModuleId { get; set; }
        public int RoleId { get; set; }
        public bool IsVisible { get; set; }
        public bool IsEditable { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModfiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
