//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayPeriodHistory
    {
        public int PayPediorHistoryId { get; set; }
        public Nullable<int> PayPeriodId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> HistoryDate { get; set; }
        public int UserId { get; set; }
        public string CompanyId { get; set; }
    
        public virtual PayPeriods PayPeriods { get; set; }
    }
}
