//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayPeriodHour
    {
        public int PayPeriodHoursId { get; set; }
        public int UserId { get; set; }
        public int PayPeriodId { get; set; }
        public int PayPeriodHours { get; set; }
        public string CompanyId { get; set; }
    }
}
