//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayPeriods
    {
        public PayPeriods()
        {
            this.ClockProfiles = new HashSet<ClockProfile>();
            this.CompensatoryEmployeeHistory = new HashSet<CompensatoryEmployeeHistory>();
            this.PayPeriodHistory = new HashSet<PayPeriodHistory>();
            this.TimesheetPolicies = new HashSet<TimesheetPolicy>();
        }
    
        public int PayPeriodId { get; set; }
        public System.Guid PayPeriodCode { get; set; }
        public string PayPeriodDescription { get; set; }
        public Nullable<int> PayPeriodTypeId { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public string StartDayOfWeek { get; set; }
        public bool NextSchedule { get; set; }
        public int CompanyId { get; set; }
        public Nullable<System.DateTime> PayPeriodCheckDate { get; set; }
    
        public virtual ICollection<ClockProfile> ClockProfiles { get; set; }
        public virtual ICollection<CompensatoryEmployeeHistory> CompensatoryEmployeeHistory { get; set; }
        public virtual ICollection<PayPeriodHistory> PayPeriodHistory { get; set; }
        public virtual ICollection<TimesheetPolicy> TimesheetPolicies { get; set; }
    }
}
