//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateMatrix
    {
        public RateMatrix()
        {
            this.TimesheetPolicies = new HashSet<TimesheetPolicy>();
        }
    
        public int RateMatrixId { get; set; }
        public int UserId { get; set; }
        public string RateMatrixType { get; set; }
        public int DeptJobId { get; set; }
        public Nullable<decimal> PayRate { get; set; }
        public Nullable<decimal> BillRate { get; set; }
        public int CompanyId { get; set; }
    
        public virtual ICollection<TimesheetPolicy> TimesheetPolicies { get; set; }
    }
}
