//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecruitingQuestions
    {
        public RecruitingQuestions()
        {
            this.RecruitingAnswers = new HashSet<RecruitingAnswers>();
            this.JobProfile = new HashSet<JobProfile>();
        }
    
        public int RecruitingQuestionId { get; set; }
        public System.Guid RecruitingQuestionCode { get; set; }
        public int CompanyID { get; set; }
        public string QuestionText { get; set; }
        public int QuestionType { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Required { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<RecruitingAnswers> RecruitingAnswers { get; set; }
        public virtual ICollection<JobProfile> JobProfile { get; set; }
    }
}
