//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecruitingAnswers
    {
        public int AnswerId { get; set; }
        public int QuestionId { get; set; }
        public int QuestionTypeId { get; set; }
        public string Answers { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<bool> KnockOutValue { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual RecruitingQuestions RecruitingQuestions { get; set; }
    }
}
