//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportList
    {
        public int ReportItemId { get; set; }
        public string ReportGroupName { get; set; }
        public string ReportName { get; set; }
        public string ReportDescription { get; set; }
        public string ReportAction { get; set; }
        public bool IsInclude { get; set; }
        public int RoleId { get; set; }
        public int CompanyId { get; set; }
    }
}
