//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewScore
    {
        public int ReviewScoreId { get; set; }
        public Nullable<System.Guid> ReviewScoreCode { get; set; }
        public Nullable<double> Question { get; set; }
        public Nullable<double> Accountability { get; set; }
        public Nullable<double> Competency { get; set; }
        public Nullable<double> Goal { get; set; }
        public Nullable<int> ReviewId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<bool> WeightedAverage { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual Review Review { get; set; }
    }
}
