//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public Review()
        {
            this.ReviewSchedules = new HashSet<ReviewSchedule>();
            this.Reviewees = new HashSet<Reviewee>();
            this.ReviewScores = new HashSet<ReviewScore>();
        }
    
        public int ReviewId { get; set; }
        public Nullable<System.Guid> ReviewCode { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> HRManagerId { get; set; }
        public string HRComments { get; set; }
        public Nullable<int> HRStatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<ReviewSchedule> ReviewSchedules { get; set; }
        public virtual ICollection<Reviewee> Reviewees { get; set; }
        public virtual ICollection<ReviewScore> ReviewScores { get; set; }
    }
}
