//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviewee
    {
        public int RevieweeId { get; set; }
        public Nullable<System.Guid> RevieweeCode { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Type { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ReviewId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<int> JobTitleId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual Review Review { get; set; }
    }
}
