//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewReviewer
    {
        public int ReviewReviewerId { get; set; }
        public Nullable<System.Guid> ReviewReviewerCode { get; set; }
        public Nullable<int> ReviewId { get; set; }
        public Nullable<int> ReviewerMasterId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
