//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleMaster
    {
        public RoleMaster()
        {
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int RoleMasterId { get; set; }
        public Nullable<System.Guid> RoleId { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
