//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public int RuleId { get; set; }
        public int RuleErrorLogId { get; set; }
        public string RuleName { get; set; }
        public string RuleDescription { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CompanyId { get; set; }
    }
}
