//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleEmployee
    {
        public ScheduleEmployee()
        {
            this.ScheduleArchiveEmployees = new HashSet<ScheduleArchiveEmployee>();
        }
    
        public int ScheduleEmployeeId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<double> LunchMinutes { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public bool IsScheduleActive { get; set; }
        public int CompanyId { get; set; }
    
        public virtual ICollection<ScheduleArchiveEmployee> ScheduleArchiveEmployees { get; set; }
    }
}
