//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheet
    {
        public Timesheet()
        {
            this.TimesheetArchives = new HashSet<TimesheetArchive>();
            this.TimesheetArchiveShifts = new HashSet<TimesheetArchiveShift>();
            this.TimesheetAudits = new HashSet<TimesheetAudit>();
            this.TimesheetShifts = new HashSet<TimesheetShift>();
        }
    
        public int TimesheetId { get; set; }
        public int UserId { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<double> LunchMinutes { get; set; }
        public Nullable<int> PayTypeId { get; set; }
        public string PunchType { get; set; }
        public string PayCode { get; set; }
        public string PayType { get; set; }
        public string PayTypeDescription { get; set; }
        public Nullable<int> TimeType { get; set; }
        public Nullable<int> HomeDivisionId { get; set; }
        public string HomeDivisionDescription { get; set; }
        public Nullable<int> HomeDepartmentId { get; set; }
        public string HomeDepartmentDescription { get; set; }
        public string WorkDepartmentId { get; set; }
        public string WorkDepartmentDescription { get; set; }
        public string WorkJobId { get; set; }
        public string WorkJobDescription { get; set; }
        public Nullable<int> WorkLevel4Id { get; set; }
        public string WorkLevel4Description { get; set; }
        public Nullable<int> WorkLevel5Id { get; set; }
        public string WorkLevel5Description { get; set; }
        public Nullable<System.DateTime> StartRound { get; set; }
        public Nullable<System.DateTime> EndRound { get; set; }
        public Nullable<double> RegHours { get; set; }
        public Nullable<double> OTHours { get; set; }
        public Nullable<double> DTHours { get; set; }
        public Nullable<double> TotalTime { get; set; }
        public Nullable<decimal> Dollars { get; set; }
        public Nullable<decimal> PayRate { get; set; }
        public Nullable<decimal> TotalPayDollars { get; set; }
        public Nullable<decimal> BillRate { get; set; }
        public Nullable<decimal> TotalBillDollars { get; set; }
        public Nullable<decimal> TotalDollars { get; set; }
        public string Exception { get; set; }
        public Nullable<int> PayPeriodId { get; set; }
        public string PayPeriodDescription { get; set; }
        public Nullable<int> ScheduleMasterId { get; set; }
        public Nullable<int> ShiftMasterId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public string ShiftDescription { get; set; }
        public Nullable<int> OvertimeId { get; set; }
        public string OverTimeDescription { get; set; }
        public Nullable<bool> AccrueToOT { get; set; }
        public Nullable<decimal> SatPremium { get; set; }
        public Nullable<decimal> SunPremium { get; set; }
        public Nullable<double> RegTCompensation { get; set; }
        public Nullable<double> OTCompensation { get; set; }
        public Nullable<double> DTCompensation { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<byte> Protect { get; set; }
        public string Notes { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> StartLocationId { get; set; }
        public Nullable<byte> StartLocationType { get; set; }
        public string StartLocationName { get; set; }
        public byte[] StartDeviceNumber { get; set; }
        public Nullable<int> EndLocationId { get; set; }
        public Nullable<byte> EndLocationType { get; set; }
        public string EndLocationName { get; set; }
        public string EndDeviceNumber { get; set; }
        public string InTimeZone { get; set; }
        public string OutTimeZone { get; set; }
        public string AdminNotes { get; set; }
        public string ManagerNotes { get; set; }
        public string EmployeeNotes { get; set; }
        public Nullable<bool> OTExceptionVerified { get; set; }
        public int CompanyId { get; set; }
    
        public virtual ICollection<TimesheetArchive> TimesheetArchives { get; set; }
        public virtual ICollection<TimesheetArchiveShift> TimesheetArchiveShifts { get; set; }
        public virtual ICollection<TimesheetAudit> TimesheetAudits { get; set; }
        public virtual ICollection<TimesheetShift> TimesheetShifts { get; set; }
        public virtual PayType PayType1 { get; set; }
    }
}
