//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimesheetPolicy
    {
        public int TimesheetPolicyId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ReportToUserId { get; set; }
        public Nullable<int> TimesheetTypeId { get; set; }
        public Nullable<bool> AllowTimesheet { get; set; }
        public Nullable<int> EmploymentStatus { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> JobProfileId { get; set; }
        public Nullable<int> Level4Id { get; set; }
        public Nullable<int> Level5Id { get; set; }
        public Nullable<int> PayPeriodId { get; set; }
        public Nullable<decimal> PayRate { get; set; }
        public Nullable<decimal> BillRate { get; set; }
        public Nullable<int> HolidayGroupId { get; set; }
        public Nullable<int> LunchId { get; set; }
        public Nullable<int> RoundingId { get; set; }
        public Nullable<int> OvertimeId { get; set; }
        public Nullable<bool> IsScheduleRequire { get; set; }
        public Nullable<int> ShiftMasterId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<int> PTOMasterId { get; set; }
        public Nullable<System.DateTime> BenefitAnnivarsaryDate { get; set; }
        public Nullable<System.DateTime> BenefitStartDate { get; set; }
        public Nullable<int> RateMatrixId { get; set; }
        public Nullable<int> CompensatoryId { get; set; }
        public Nullable<int> ClockProfileId { get; set; }
        public Nullable<decimal> WorkedToDdateHours { get; set; }
        public Nullable<System.DateTime> NextScheduleStartDate { get; set; }
        public string Notes { get; set; }
        public int CompanyId { get; set; }
    
        public virtual CompensatoryTimePlan CompensatoryTimePlan { get; set; }
        public virtual Lunch Lunch { get; set; }
        public virtual RateMatrix RateMatrix { get; set; }
        public virtual Rounding Rounding { get; set; }
        public virtual TimeOffMaster TimeOffMaster { get; set; }
        public virtual TimesheetType TimesheetType { get; set; }
        public virtual OverTimePolicy OverTimePolicy { get; set; }
        public virtual PayPeriods PayPeriods { get; set; }
    }
}
