//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeProfile
    {
        public int TimeProfileId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
        public string TimeProfileName { get; set; }
        public string PayPeriod { get; set; }
        public Nullable<decimal> PayRate { get; set; }
        public Nullable<decimal> BillRate { get; set; }
        public string Schedule { get; set; }
        public string LunchCode { get; set; }
        public string Holiday { get; set; }
        public string Rounding { get; set; }
        public string RateMatrix { get; set; }
        public string Shift { get; set; }
        public string ShiftGroup { get; set; }
        public string CompensatoryCode { get; set; }
        public string PayPolicy { get; set; }
        public string PTOCode { get; set; }
        public string SelectionType { get; set; }
        public string NoOffDays { get; set; }
        public string TimesheetType { get; set; }
        public Nullable<bool> AlloTimesheet { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
