//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeOffMaster
    {
        public TimeOffMaster()
        {
            this.TimeOffEmployees = new HashSet<TimeOffEmployee>();
            this.TimeOffEmployeeHistories = new HashSet<TimeOffEmployeeHistory>();
            this.TimeOffPlans = new HashSet<TimeOffPlan>();
            this.TimeOffServices = new HashSet<TimeOffService>();
            this.TimesheetPolicies = new HashSet<TimesheetPolicy>();
        }
    
        public int PTOMasterId { get; set; }
        public System.Guid PTOCode { get; set; }
        public string PTODescription { get; set; }
        public int CompanyId { get; set; }
    
        public virtual ICollection<TimeOffEmployee> TimeOffEmployees { get; set; }
        public virtual ICollection<TimeOffEmployeeHistory> TimeOffEmployeeHistories { get; set; }
        public virtual ICollection<TimeOffPlan> TimeOffPlans { get; set; }
        public virtual ICollection<TimeOffService> TimeOffServices { get; set; }
        public virtual ICollection<TimesheetPolicy> TimesheetPolicies { get; set; }
    }
}
