//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimesheetShift
    {
        public TimesheetShift()
        {
            this.TimesheetArchiveShifts = new HashSet<TimesheetArchiveShift>();
        }
    
        public int TimesheetShiftId { get; set; }
        public int UserId { get; set; }
        public int TimesheetId { get; set; }
        public int ShiftMasterId { get; set; }
        public int ShiftWorkId { get; set; }
        public int ShiftAdjustedId { get; set; }
        public byte DayOfWeek { get; set; }
        public Nullable<int> ShiftRegHours { get; set; }
        public Nullable<int> ShiftOTHours { get; set; }
        public Nullable<int> ShiftDTHours { get; set; }
        public Nullable<int> LunchHours { get; set; }
        public Nullable<int> ShiftTotalHours { get; set; }
        public Nullable<decimal> ShiftDolarRate { get; set; }
        public Nullable<decimal> ShiftCalcAmout { get; set; }
        public Nullable<decimal> ShiftOverrideAmount { get; set; }
        public Nullable<decimal> ShiftCalcAmountBill { get; set; }
        public bool MeetsMinimum { get; set; }
        public Nullable<int> ShiftStartCount { get; set; }
        public Nullable<int> DeleteRec { get; set; }
        public int CompanyId { get; set; }
    
        public virtual Timesheet Timesheet { get; set; }
        public virtual ICollection<TimesheetArchiveShift> TimesheetArchiveShifts { get; set; }
    }
}
