//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeOffEmployee
    {
        public int TimeOffUserId { get; set; }
        public int UserId { get; set; }
        public int PTOMasterId { get; set; }
        public int PayTypeId { get; set; }
        public string PayCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> MaxTime { get; set; }
        public Nullable<double> AccruedTime { get; set; }
        public double Earned { get; set; }
        public Nullable<double> CarryForward { get; set; }
        public Nullable<double> TimeTaken { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> AccrualBalance { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public int CompanyId { get; set; }
    
        public virtual TimeOffMaster TimeOffMaster { get; set; }
        public virtual PayType PayType { get; set; }
    }
}
