//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingClass
    {
        public TrainingClass()
        {
            this.TrainingClassResource = new HashSet<TrainingClassResource>();
        }
    
        public int TrainingClassId { get; set; }
        public Nullable<System.Guid> TrainingClassCode { get; set; }
        public string TrainingClassName { get; set; }
        public string TrainingClassDescription { get; set; }
        public Nullable<decimal> TrainingClassCost { get; set; }
        public Nullable<decimal> TrainingClassHours { get; set; }
        public Nullable<int> TrainingClassImage { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual TrainingClass TrainingClass1 { get; set; }
        public virtual TrainingClass TrainingClass2 { get; set; }
        public virtual ICollection<TrainingClassResource> TrainingClassResource { get; set; }
    }
}
