//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingClassSchedule
    {
        public int TrainingClassScheduleId { get; set; }
        public Nullable<int> TrainingClassId { get; set; }
        public System.Guid TrainingClassScheduleCode { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime EnrollmentStartDate { get; set; }
        public System.DateTime EnrollmentEndDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
