//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingClassResource
    {
        public int TrainingClassResourceId { get; set; }
        public System.Guid TrainingClassResourceCode { get; set; }
        public int TrainingClassId { get; set; }
        public int Attachment { get; set; }
        public string FileName { get; set; }
        public string ContentType { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual TrainingClass TrainingClass { get; set; }
    }
}
