//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variable
    {
        public int mvId { get; set; }
        public string mvKeyDesc { get; set; }
        public Nullable<short> mvInt1 { get; set; }
        public Nullable<short> mvInt2 { get; set; }
        public Nullable<short> mvInt3 { get; set; }
        public Nullable<System.DateTime> mvTime1 { get; set; }
        public string mvText1 { get; set; }
        public string mvText2 { get; set; }
        public string mvText3 { get; set; }
        public Nullable<int> mvID1 { get; set; }
        public Nullable<int> mvId2 { get; set; }
        public Nullable<int> mvId3 { get; set; }
        public Nullable<System.DateTime> mvDate1 { get; set; }
        public Nullable<System.DateTime> mvDate2 { get; set; }
        public Nullable<System.DateTime> mvDate3 { get; set; }
        public bool mvBit1 { get; set; }
        public bool mvBit2 { get; set; }
        public bool mvBit3 { get; set; }
        public Nullable<decimal> mvCur1 { get; set; }
        public Nullable<decimal> mvCur2 { get; set; }
        public Nullable<decimal> mvCur3 { get; set; }
        public string CompanyCode { get; set; }
        public int Id { get; set; }
    }
}
