//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkAuthorization
    {
        public WorkAuthorization()
        {
            this.WorkAuthorizationDocumentation = new HashSet<WorkAuthorizationDocumentation>();
        }
    
        public int WorkAuthorizationId { get; set; }
        public System.Guid WorkAuthorizationCode { get; set; }
        public int CompanyId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public Nullable<System.DateTime> EmployeeSignDate { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> CitizenOfUS { get; set; }
        public string AlienNumber { get; set; }
        public Nullable<System.DateTime> PermanentResidentExpire { get; set; }
        public Nullable<int> AlienCitizenof { get; set; }
        public Nullable<System.DateTime> AlienAuthorisedDate { get; set; }
        public Nullable<int> AlienAuthorisedCitizenof { get; set; }
        public Nullable<bool> FederalLaw { get; set; }
        public Nullable<bool> IsSSN { get; set; }
        public Nullable<bool> IsEmployeeSign { get; set; }
        public Nullable<int> EmployeeSignId { get; set; }
        public string Confirmation { get; set; }
        public Nullable<System.DateTime> EmploymentOn { get; set; }
        public Nullable<bool> IsEmployerSign { get; set; }
        public Nullable<int> EmployerSignId { get; set; }
        public string EmployerUserId { get; set; }
        public string EmployerTransactionId { get; set; }
        public Nullable<System.DateTime> EmployerSignDate { get; set; }
        public Nullable<System.DateTime> CertificationDate { get; set; }
        public byte[] Attachment { get; set; }
        public string AttachmentType { get; set; }
        public string AttachmentName { get; set; }
        public string AlienRegistrationNumber { get; set; }
        public string AdmissionNumber { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<int> Countryof { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<WorkAuthorizationDocumentation> WorkAuthorizationDocumentation { get; set; }
        public virtual WorkAuthorization WorkAuthorization1 { get; set; }
        public virtual WorkAuthorization WorkAuthorization2 { get; set; }
    }
}
