//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Service.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkAuthorizationDocumentation
    {
        public int Id { get; set; }
        public int WorkAuthorizationDocumentationTypeId { get; set; }
        public int WorkAuthorizationId { get; set; }
        public Nullable<int> DocumentTitle { get; set; }
        public string DocumentIssuingAuthority { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual WorkAuthorization WorkAuthorization { get; set; }
    }
}
